# Generated by Django 2.0.4 on 2019-03-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_auto_20190224_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
