# Generated by Django 2.0.4 on 2019-03-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_article_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_time',
        ),
    ]
