# Generated by Django 2.0.4 on 2019-03-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_auto_20190309_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
