"""
Django settings for talkrobot project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 可以把多个app放在这个目录下
# sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '28k)9c9%t%9k99cm28=2(@m95$akrweui8#1*0g^3%29l30a_8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'crispy_forms',
    'reversion',
    'ckeditor',
    #富文本编辑器注册
    'ckeditor_uploader',
    #图片上传
    'robot.apps.RobotConfig',
    'read_statistics',
    'comment',
    'likes',
    'user',
]
SITE_ID = 1  #为了指定django.contrib.sites


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'talkrobot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #在这里设置全局都可以访问的，这个DIRS路径指向根目录下的templates
        'DIRS': [
            os.path.join(BASE_DIR,'templates'),
            os.path.join(BASE_DIR,'user/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 可以在公共模板中引用，这个login用于在页面中弹出登录框
                'user.context_processors.login_model_form',
            ],
        },
    },
]

WSGI_APPLICATION = 'talkrobot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_web3',
        'USER': 'root',
        'PASSWORD': 'liusheng',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
#超级管理员 liusheng 1314520ls

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
#静态文件的根目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
# STATIC_ROOT = os.path.join(BASE_DIR,'static/')

#media，保存上传的文件
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

#配置ckeditor的上传路径
CKEDITOR_UPLOAD_PATH = 'upload/'
# 配置评论的富文本编辑
CKEDITOR_CONFIGS = {
    'default':{},
    'comment_ckeditor':{
        'toolbar':'custom',
        'toolbar_custom':[
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ["TextColor","BGColor","RemoveFormat"],
            ["NumberedList",'BulletedList'],
            ['Link','Unlink'],
            ["Smiley","SpecialChar","Blockquote"],
        ],
        'width':'auto',
        'height':'160',
        'tableSpaces':4,
        # 去除底部的部分  4600249367272
        'removePlugins':'elementspath',
        'resize_enabled':False,
    }
}

#自定义参数
EACH_PAGE_BLOGS_NUM = 4

#数据库缓存
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

# 发送邮件配置
# https://docs.djangoproject.com/en/2.1/topics/email/
# https://docs.djangoproject.com/en/2.1/search/?q=email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '947172572@qq.com'
EMAIL_HOST_PASSWORD = 'pocnwbatjyndbbhg' #授权码
EMAIL_SUBJECT_PREFIX = '[刘胜的博客]'
EMAIL_USE_TLS = True  # 与SMTP服务器通信时，是否启动TLS链接（安全链接）